### ISSUE TITLE
Variable declaration and initialization can be done within for loop declaration

### ISSUE THREAD

**Issue by nishant-jain-94** [sro-boeing-wave-2/reverse-string-js-problem-angita1#1]
https://github.com/sro-boeing-wave-2/reverse-string-js-problem-angita1/blob/c2510c3ee05acd6a856b7e8a4af18a4d0a886e67/reverse-using-iterators.js#L4-L6

**Comment by yaiphabee** [comment]
done initialization and declaration in one line
