### ISSUE TITLE
Using es6 arrow functions without return keyword

### ISSUE THREAD

**Issue by nishant-jain-94** [sro-boeing-wave-2/reverse-string-js-problem-angita1#2]
https://github.com/sro-boeing-wave-2/reverse-string-js-problem-angita1/blob/c2510c3ee05acd6a856b7e8a4af18a4d0a886e67/reverse-using-built-in-function.js#L3-L6

**Comment by nishant-jain-94** [comment]
Arrow functions https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions

**Comment by yaiphabee** [comment]
Used arrow functions
